const CONFIG = {
    introTitle: 'My Dear',
    introDesc: `Im writing this to reply for everything u thought, but u havent intend to tell me any thing.`,
    btnIntro: 'Stop being that much sensitive',
    title: 'I love u very much',
    desc: 'It's just a word, how can I do it usually when we're in long distance love ',
    btnYes: 'U still love me?',
    btnNo: 'Không',
    question:'Xem phim ko?',
    btnReply: '"accepting my sexuality"?',
    reply: 'Có cái gì muốn nói thì nói ra',
    messDesc: 'đồng ý xem phim thì rep ở đây',
    btnAccept: 'ờ',
    messLink: 'https://www.facebook.com/hha.019/',
